
package Jframe;
import all_classes.FileReadWrite;
import all_classes.SoundPlay;
import all_classes.database_con;
import all_classes.fileOpen;
import all_classes.openURL;
import java.awt.Rectangle;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.URISyntaxException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.sound.sampled.Clip;
import javax.sound.sampled.FloatControl;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class Index extends javax.swing.JFrame {

    /**
     * Creates new form Index
     */
    Clip active=SoundPlay.play("bgnew.wav");
    int off_on=1;
    int resume=0;
    public Index() throws FileNotFoundException {
        initComponents();
        nbt.setIcon(new javax.swing.ImageIcon("img\\icon\\reload.png"));
        sbt.setIcon(new javax.swing.ImageIcon("img\\icon\\sta.png"));
        rbt.setIcon(new javax.swing.ImageIcon("img\\icon\\reset.png"));
        ebt.setIcon(new javax.swing.ImageIcon("img\\icon\\exit.png"));
        enbt.setIcon(new javax.swing.ImageIcon("img\\icon\\thik_mark.png"));
        dbt.setIcon(new javax.swing.ImageIcon("img\\icon\\Cancel.png"));
        cbt.setIcon(new javax.swing.ImageIcon("img\\icon\\camera.png"));
        obt.setIcon(new javax.swing.ImageIcon("img\\icon\\folder.png"));
        vbt.setIcon(new javax.swing.ImageIcon("img\\icon\\help.gif"));
        fbt.setIcon(new javax.swing.ImageIcon("img\\icon\\mail.png"));
        abt.setIcon(new javax.swing.ImageIcon("img\\icon\\info.gif"));
        bg.setIcon(new javax.swing.ImageIcon("img\\icon\\bg.jpg"));
        active.loop(Clip.LOOP_CONTINUOUSLY);
        iconset();
        ImageIcon img=new ImageIcon("img\\icon\\tt.png");
        this.setIconImage(img.getImage());
        toltip();
       // private nCurrent_score dlg=new Current_score(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_panel = new javax.swing.JDesktopPane();
        Center_panel = new javax.swing.JPanel();
        First_line = new javax.swing.JPanel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        Second_line = new javax.swing.JPanel();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        bg = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        nbt = new javax.swing.JMenuItem();
        sbt = new javax.swing.JMenuItem();
        rbt = new javax.swing.JMenuItem();
        ebt = new javax.swing.JMenuItem();
        sound = new javax.swing.JMenu();
        enbt = new javax.swing.JMenuItem();
        dbt = new javax.swing.JMenuItem();
        picture = new javax.swing.JMenu();
        cbt = new javax.swing.JMenuItem();
        obt = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        vbt = new javax.swing.JMenuItem();
        fbt = new javax.swing.JMenuItem();
        abt = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fruits Finding");
        setMinimumSize(new java.awt.Dimension(650, 670));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        bg_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bg_panelMouseEntered(evt);
            }
        });

        Center_panel.setOpaque(false);

        First_line.setOpaque(false);

        b1.setToolTipText("");
        b1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b1MouseExited(evt);
            }
        });
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setToolTipText("");
        b2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b2MouseExited(evt);
            }
        });
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setToolTipText("");
        b3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b3MouseExited(evt);
            }
        });
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout First_lineLayout = new javax.swing.GroupLayout(First_line);
        First_line.setLayout(First_lineLayout);
        First_lineLayout.setHorizontalGroup(
            First_lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(First_lineLayout.createSequentialGroup()
                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        First_lineLayout.setVerticalGroup(
            First_lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Second_line.setOpaque(false);
        Second_line.setPreferredSize(new java.awt.Dimension(582, 291));

        b4.setToolTipText("");
        b4.setOpaque(false);
        b4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b4MouseExited(evt);
            }
        });
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b5.setToolTipText("");
        b5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b5MouseExited(evt);
            }
        });
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b6.setToolTipText("");
        b6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b6MouseExited(evt);
            }
        });
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Second_lineLayout = new javax.swing.GroupLayout(Second_line);
        Second_line.setLayout(Second_lineLayout);
        Second_lineLayout.setHorizontalGroup(
            Second_lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Second_lineLayout.createSequentialGroup()
                .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Second_lineLayout.setVerticalGroup(
            Second_lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout Center_panelLayout = new javax.swing.GroupLayout(Center_panel);
        Center_panel.setLayout(Center_panelLayout);
        Center_panelLayout.setHorizontalGroup(
            Center_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Center_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Center_panelLayout.createSequentialGroup()
                    .addGap(10, 19, Short.MAX_VALUE)
                    .addGroup(Center_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(First_line, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Second_line, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(0, 9, Short.MAX_VALUE)))
        );
        Center_panelLayout.setVerticalGroup(
            Center_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Center_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Center_panelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(First_line, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Second_line, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        bg_panel.add(Center_panel);
        Center_panel.setBounds(30, 10, 610, 590);
        bg_panel.add(bg);
        bg.setBounds(0, 0, 690, 620);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Game");

        nbt.setMnemonic('o');
        nbt.setText("Reload");
        nbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbtActionPerformed(evt);
            }
        });
        fileMenu.add(nbt);

        sbt.setMnemonic('a');
        sbt.setText("Score");
        sbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbtActionPerformed(evt);
            }
        });
        fileMenu.add(sbt);

        rbt.setText("Restore Settings");
        rbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtActionPerformed(evt);
            }
        });
        fileMenu.add(rbt);

        ebt.setMnemonic('x');
        ebt.setText("Exit");
        ebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ebtActionPerformed(evt);
            }
        });
        fileMenu.add(ebt);

        menuBar.add(fileMenu);

        sound.setText("Sound");

        enbt.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        enbt.setText("Enable");
        enbt.setToolTipText("");
        enbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enbtActionPerformed(evt);
            }
        });
        sound.add(enbt);

        dbt.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        dbt.setText("Disable");
        dbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbtActionPerformed(evt);
            }
        });
        sound.add(dbt);

        menuBar.add(sound);

        picture.setText("Picture");

        cbt.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        cbt.setText("Capture");
        cbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtActionPerformed(evt);
            }
        });
        picture.add(cbt);

        obt.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        obt.setText("Open image folder");
        obt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obtActionPerformed(evt);
            }
        });
        picture.add(obt);

        menuBar.add(picture);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        vbt.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        vbt.setMnemonic('c');
        vbt.setText("View Help");
        vbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vbtActionPerformed(evt);
            }
        });
        helpMenu.add(vbt);

        fbt.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        fbt.setText("Feedback");
        fbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fbtActionPerformed(evt);
            }
        });
        helpMenu.add(fbt);

        abt.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        abt.setMnemonic('a');
        abt.setText("About Fruits Finding");
        abt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abtActionPerformed(evt);
            }
        });
        helpMenu.add(abt);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ebtActionPerformed
     int n=JOptionPane.showConfirmDialog(null, "Are you Sure want to exit ?", "Game Exit !",JOptionPane.YES_NO_OPTION);
      if(n==0)
      {
          System.exit(0);
      }
    }//GEN-LAST:event_ebtActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
     int n=JOptionPane.showConfirmDialog(null, "Are you Sure want to exit ?", "Game Exit !",JOptionPane.YES_NO_OPTION);
      if(n==0)
      {
          System.exit(0);
      }
      else {
     }
    }//GEN-LAST:event_formWindowClosing

    private void obtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obtActionPerformed
     try{
            String nameee= System.getProperty("user.name");
            String folder= "C:\\Users\\"+nameee+"\\Documents\\Fruits Finding";     
            fileOpen.checker(folder);
        }catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_obtActionPerformed

    private void cbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtActionPerformed
        try{
            String nameee= System.getProperty("user.name");
            File folder= new File("C:/Users/"+nameee+"/Documents/Fruits Finding");
            if(!(folder.exists()))
            {
                folder.mkdir();
            }
            Rectangle rt=new Rectangle(Toolkit.getDefaultToolkit().getScreenSize());
            BufferedImage img=new Robot().createScreenCapture(rt);
            ImageIcon icon=new ImageIcon(img);
            int img_cnt=FileReadWrite.FileOutput("count")+1;
            String cap="\\Fruits_Finding_"+img_cnt+".png";
            ImageIO.write(img, "png", new File("C:\\Users\\"+nameee+"\\Documents\\Fruits Finding"+cap));         
            fileOpen.checker("C:\\Users\\"+nameee+"\\Documents\\Fruits Finding"+cap);  
            FileReadWrite.FileInput(img_cnt, "count");
        }catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_cbtActionPerformed

    private void dbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbtActionPerformed
        active.stop();
        off_on=0;
    }//GEN-LAST:event_dbtActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        active.stop();
                resume=1;        
                Level_One n = new Level_One(new javax.swing.JFrame(), true,off_on);
                n.setVisible(true);
                
        
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        try {
            value_get();
            if(l2==1)
            {
                active.stop();
                resume=1; 
                Level_Two n = new Level_Two(new javax.swing.JFrame(), true,off_on);
                n.setVisible(true);
            }
            else
            {
                Clip cp=SoundPlay.play("Complete.wav");
                cp.start();
                JOptionPane.showMessageDialog(this, "You have to Unlock at first.\nHints:Complate the previous level.", "Alert", JOptionPane.OK_OPTION);
            }
            
        } catch (IOException ex) {
            Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        try {
            value_get();
            if(l3==1)
            {
                active.stop();
                resume=1; 
                Level_Three dialog = new Level_Three(new javax.swing.JFrame(), true,off_on);
                dialog.setVisible(true);
            }
            else
                {
                Clip cp=SoundPlay.play("Complete.wav");
                cp.start();
                JOptionPane.showMessageDialog(this, "You have to Unlock at first.\nHints:Complate the previous level.", "Alert", JOptionPane.OK_OPTION);
            }
            } catch (IOException ex) {
            Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        try {
            value_get();
            if(l4==1)
            {
                active.stop();
                resume=1; 
                Level_Four n = new Level_Four(new javax.swing.JFrame(), true,off_on);
                n.setVisible(true);
            }
            else
                {
                Clip cp=SoundPlay.play("Complete.wav");
                cp.start();
                JOptionPane.showMessageDialog(this, "You have to Unlock at first.\nHints:Complate the previous level.", "Alert", JOptionPane.OK_OPTION);
            }
        } catch (IOException ex) {
            Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        try {
            value_get();
            if(l5==1)
            {
                active.stop();
                resume=1; 
                Level_Five n = new Level_Five(new javax.swing.JFrame(), true,off_on);
                n.setVisible(true);
            }
            else
                {
                Clip cp=SoundPlay.play("Complete.wav");
                cp.start();
                JOptionPane.showMessageDialog(this, "You have to Unlock at first.\nHints:Complate the previous level.", "Alert", JOptionPane.OK_OPTION);
            }
        } catch (IOException ex) {
            Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        try {
            value_get();
            if(l6==1)
            {
                active.stop();
                resume=1; 
                Level_Six n = new Level_Six(new javax.swing.JFrame(), true,off_on);
                n.setVisible(true);
            }
            else
                {
                Clip cp=SoundPlay.play("Complete.wav");
                cp.start();
                JOptionPane.showMessageDialog(this, "You have to Unlock at first.\nHints:Complate the previous level.", "Alert", JOptionPane.OK_OPTION);
            }
        } catch (IOException ex) {
            Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b6ActionPerformed

    private void vbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vbtActionPerformed
     vHelp n=new vHelp();
     n.setVisible(true);
    }//GEN-LAST:event_vbtActionPerformed

    private void fbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fbtActionPerformed
        try {
            openURL.go();
        } catch (URISyntaxException ex) {
            Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_fbtActionPerformed

    private void abtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abtActionPerformed
     AFF n=new AFF();
     n.setVisible(true);
    }//GEN-LAST:event_abtActionPerformed

    private void sbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbtActionPerformed
     Statictic_from n = new Statictic_from(new javax.swing.JFrame(), true);
     n.setVisible(true);
    }//GEN-LAST:event_sbtActionPerformed

    private void rbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtActionPerformed
        int s=JOptionPane.showConfirmDialog(null, "Are you sure restore all information?\nN.B:Your previous all data will be lost.", "Confirm message!",JOptionPane.YES_NO_OPTION);
        if(s==0)
         {
        try {
            l2=0;l3=0;l4=0;l5=0;l6=0;
            value_put();
            FileReadWrite.FileInput(0, "flag");
            iconset();
            //name	totalplay	totalwon	totalloss	abandon	bsc	mt	process	others
            
            try {
                String sql="UPDATE info SET totalplay= 0, totalwon=0, totalloss=0, abandon=0, bsc=0, mt=0, process=0 , others=0";
                Connection con=database_con.db_check();
                PreparedStatement st=con.prepareStatement(sql);
                st.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "The game information reset\nsuccessfully.Let's enjoy!", "Confirm message!", JOptionPane.OK_OPTION);
        } catch (IOException ex) {
            Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
        }
          
        }
      
    }//GEN-LAST:event_rbtActionPerformed

    private void nbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbtActionPerformed
        try {
            dispose();
            
            Index n=new Index();
            n.setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_nbtActionPerformed

    private void enbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enbtActionPerformed
        active.start();
        active.loop(Clip.LOOP_CONTINUOUSLY);
        off_on=1;
    }//GEN-LAST:event_enbtActionPerformed

    private void b1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseEntered
    
    b1.setIcon(new javax.swing.ImageIcon("img\\lav 1\\1stC.png"));
    
    Clip hoverActive=SoundPlay.play("beep.wav");
    hoverActive.start();
    }//GEN-LAST:event_b1MouseEntered

    private void b1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseExited
    b1.setIcon(new javax.swing.ImageIcon("img\\lav 1\\1st.jpg"));
    }//GEN-LAST:event_b1MouseExited

    private void b2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MouseEntered
    if(l2==1)
    {
        b2.setIcon(new javax.swing.ImageIcon("img\\lav 2\\1stC.png"));
    }
    Clip hoverActive=SoundPlay.play("beep.wav");
    hoverActive.start();
    }//GEN-LAST:event_b2MouseEntered

    private void b2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MouseExited
    if(l2==1)
    {
        b2.setIcon(new javax.swing.ImageIcon("img\\lav 2\\1st.jpg"));
    }
    }//GEN-LAST:event_b2MouseExited

    private void b3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3MouseEntered
    if(l3==1)
    {
        b3.setIcon(new javax.swing.ImageIcon("img\\lav 3\\1stC.png"));
    }
    Clip hoverActive=SoundPlay.play("beep.wav");
    hoverActive.start();
    }//GEN-LAST:event_b3MouseEntered

    private void b3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3MouseExited
    if(l3==1)
    {
        b3.setIcon(new javax.swing.ImageIcon("img\\lav 3\\1st.jpg"));
    }
 
    }//GEN-LAST:event_b3MouseExited

    private void b4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b4MouseEntered
    if(l4==1)
    {
        b4.setIcon(new javax.swing.ImageIcon("img\\lav 4\\1stC.png"));
    }
    Clip hoverActive=SoundPlay.play("beep.wav");
    hoverActive.start();
    }//GEN-LAST:event_b4MouseEntered

    private void b4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b4MouseExited
    if(l4==1)
    {
        b4.setIcon(new javax.swing.ImageIcon("img\\lav 4\\1st.jpg"));
    }

    }//GEN-LAST:event_b4MouseExited

    private void b5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b5MouseEntered
    if(l5==1)
    {
        b5.setIcon(new javax.swing.ImageIcon("img\\lav 5\\1stC.png"));
    }
    Clip hoverActive=SoundPlay.play("beep.wav");
    hoverActive.start();
    }//GEN-LAST:event_b5MouseEntered

    private void b5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b5MouseExited
    if(l5==1)
    {
        b5.setIcon(new javax.swing.ImageIcon("img\\lav 5\\1st.jpg"));
    }

    }//GEN-LAST:event_b5MouseExited

    private void b6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b6MouseEntered
    if(l6==1)
    {
        b6.setIcon(new javax.swing.ImageIcon("img\\lav 6\\1stC.png"));
    }
    Clip hoverActive=SoundPlay.play("beep.wav");
    hoverActive.start();
    }//GEN-LAST:event_b6MouseEntered

    private void b6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b6MouseExited
    if(l6==1)
    {
        b6.setIcon(new javax.swing.ImageIcon("img\\lav 6\\1st.jpg"));
    }

    }//GEN-LAST:event_b6MouseExited

    private void bg_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bg_panelMouseEntered
        try {
            iconset();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(off_on==1 && resume==1)
        {
            active.start();
            active.loop(Clip.LOOP_CONTINUOUSLY);
            resume=0;
        }
        if(database_con.get_welcome()==0)
        {
            database_con.update_welcome();
            welcome n = new welcome(new javax.swing.JFrame(), true);
            n.setVisible(true);
        }
    }//GEN-LAST:event_bg_panelMouseEntered
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Index().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Center_panel;
    private javax.swing.JPanel First_line;
    private javax.swing.JPanel Second_line;
    private javax.swing.JMenuItem abt;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JLabel bg;
    private javax.swing.JDesktopPane bg_panel;
    private javax.swing.JMenuItem cbt;
    private javax.swing.JMenuItem dbt;
    private javax.swing.JMenuItem ebt;
    private javax.swing.JMenuItem enbt;
    private javax.swing.JMenuItem fbt;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem nbt;
    private javax.swing.JMenuItem obt;
    private javax.swing.JMenu picture;
    private javax.swing.JMenuItem rbt;
    private javax.swing.JMenuItem sbt;
    private javax.swing.JMenu sound;
    private javax.swing.JMenuItem vbt;
    // End of variables declaration//GEN-END:variables
    int l2,l3,l4,l5,l6;
    String lv_name[]={"1st","2nd","3rd","4th","5th","6th"};
     private void value_get() throws FileNotFoundException
     {
         l2=FileReadWrite.FileOutput(lv_name[1]);
         l3=FileReadWrite.FileOutput(lv_name[2]);
         l4=FileReadWrite.FileOutput(lv_name[3]);
         l5=FileReadWrite.FileOutput(lv_name[4]);
         l6=FileReadWrite.FileOutput(lv_name[5]);      
     }
     private void value_put() throws IOException
     {
         FileReadWrite.FileInput(l2, lv_name[1]);
         FileReadWrite.FileInput(l3, lv_name[2]);
         FileReadWrite.FileInput(l4, lv_name[3]);
         FileReadWrite.FileInput(l5, lv_name[4]);
         FileReadWrite.FileInput(l6, lv_name[5]);
     }
    private void iconset() throws FileNotFoundException {
        
        value_get();
        b1.setIcon(new javax.swing.ImageIcon("img\\lav 1\\1st.jpg"));
        if(l2==0)
            b2.setIcon(new javax.swing.ImageIcon("img\\lav 2\\lst.jpg"));
        else
            b2.setIcon(new javax.swing.ImageIcon("img\\lav 2\\1st.jpg"));
        if(l3==0)
            b3.setIcon(new javax.swing.ImageIcon("img\\lav 3\\lst.jpg"));
        else
            b3.setIcon(new javax.swing.ImageIcon("img\\lav 3\\1st.jpg"));
        if(l4==0)
            b4.setIcon(new javax.swing.ImageIcon("img\\lav 4\\lst.jpg"));
        else
            b4.setIcon(new javax.swing.ImageIcon("img\\lav 4\\1st.jpg"));
        if(l5==0)
            b5.setIcon(new javax.swing.ImageIcon("img\\lav 5\\lst.jpg"));
        else
            b5.setIcon(new javax.swing.ImageIcon("img\\lav 5\\1st.jpg"));
        if(l6==0)
            b6.setIcon(new javax.swing.ImageIcon("img\\lav 6\\lst.jpg"));
        else
            b6.setIcon(new javax.swing.ImageIcon("img\\lav 6\\1st.jpg"));
    }

    private void toltip() {
     b1.setToolTipText(null);
     b2.setToolTipText(null);
     b3.setToolTipText(null);
     b4.setToolTipText(null);
     b5.setToolTipText(null);
     b6.setToolTipText(null);
    }

    
}
