/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Jframe;

import all_classes.FileReadWrite;
import all_classes.SoundPlay;
import all_classes.database_con;
import java.awt.Color;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.Clip;
import javax.sound.sampled.FloatControl;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author CETC
 */
public class Level_Six extends javax.swing.JDialog {

    /**
     * Creates new form Level_Six
     */
    int result;
    int snd=0;
    int stop;
    
    String fname[]={"Dragon fruit","Honeydew melon","Raspberry","Banana" ,"Cherry","Graps","Peer","Galia melon","Loquat",
        "Orange Slice","Blackberry" ,"Lime" ,"Strawberry","Passion fruit" ,"Rambutan","Blackcurrant" ,"Mango" ,
        "Pineappl","Fig","Tangerines","Guava","Satsuma",
        "Coconut","Jackfruits","Lychee","Water melon","Watermelon slice","Feijoa"};
    String[] Rname=new String[12];
    private int score;
    int tm=0;
    int k;
    int err=0;
    int[] EB=new int[28];
    Clip cp=SoundPlay.play("6th.wav");
    public Level_Six(java.awt.Frame parent, boolean modal,int OFF_ON) {
        super(parent, modal);
        initComponents();
        ImageIcon img=new ImageIcon("img\\icon\\6th.png");
        this.setIconImage(img.getImage());
        lab.setIcon(new javax.swing.ImageIcon("img\\lav 6\\first.jpg"));
        make_zero();
        set_pbar();
        refresh.setEnabled(false);
        if(OFF_ON==1)
        {
            cp.start();
            cp.loop(Clip.LOOP_CONTINUOUSLY);
            FloatControl gainControl = (FloatControl) cp.getControl(FloatControl.Type.MASTER_GAIN);
            gainControl.setValue(-10.0f);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        pbar = new javax.swing.JProgressBar();
        p_lavel_value = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        b11 = new javax.swing.JButton();
        b12 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lf = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        src = new javax.swing.JLabel();
        refresh = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lab = new javax.swing.JLabel();
        stbt = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        timeP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Level 6");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Level Processing", 0, 0, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(102, 153, 255))); // NOI18N

        p_lavel_value.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Total process:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pbar, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p_lavel_value, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(pbar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p_lavel_value, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(b4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b10, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(b7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b12, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(b11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(b1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(b4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b11, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(b5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Remaining life", 0, 0, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(51, 204, 255))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(0, 204, 255));

        lf.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lf.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lf.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lf, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lf, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Points", 0, 0, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(51, 153, 255))); // NOI18N

        src.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        src.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        src.setText("0");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(src, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(src, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        jPanel1.setLayout(null);

        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 310, 30, 30);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(460, 50, 40, 40);

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(570, 310, 30, 40);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(530, 370, 40, 30);

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 300, 30, 20);

        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6);
        jLabel6.setBounds(150, 410, 40, 40);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7);
        jLabel7.setBounds(90, 140, 40, 30);

        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8);
        jLabel8.setBounds(120, 90, 20, 30);

        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9);
        jLabel9.setBounds(160, 240, 40, 30);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10);
        jLabel10.setBounds(90, 20, 160, 40);

        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11);
        jLabel11.setBounds(540, 280, 30, 30);

        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel13);
        jLabel13.setBounds(290, 130, 30, 30);

        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel14);
        jLabel14.setBounds(280, 200, 60, 30);

        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel15);
        jLabel15.setBounds(360, 250, 30, 50);

        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel16);
        jLabel16.setBounds(260, 320, 30, 30);

        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel17);
        jLabel17.setBounds(430, 230, 40, 40);

        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel18);
        jLabel18.setBounds(20, 100, 50, 30);

        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel19);
        jLabel19.setBounds(140, 300, 40, 50);

        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel20);
        jLabel20.setBounds(40, 270, 30, 20);

        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel21);
        jLabel21.setBounds(460, 340, 40, 40);

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel22);
        jLabel22.setBounds(530, 60, 60, 40);

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel23);
        jLabel23.setBounds(280, 170, 20, 20);

        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel24);
        jLabel24.setBounds(340, 90, 60, 30);

        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel25);
        jLabel25.setBounds(270, 240, 30, 30);

        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel26);
        jLabel26.setBounds(430, 294, 40, 30);

        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel27);
        jLabel27.setBounds(320, 320, 30, 20);

        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel28);
        jLabel28.setBounds(520, 240, 20, 20);

        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel29);
        jLabel29.setBounds(40, 130, 50, 30);

        lab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lab);
        lab.setBounds(0, 0, 610, 450);

        stbt.setText("Start");
        stbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stbtActionPerformed(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Time", 0, 0, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(153, 153, 255))); // NOI18N

        timeP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        timeP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        timeP.setText("0");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(timeP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(timeP, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(stbt, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(refresh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stbt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4ActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        if(refresh.getText().equalsIgnoreCase("Abandon"))
        {
            refresh.setText("Refresh");
            if(Game_running_flag==1)
            {
                database_con.Abandon_count("lav6");
                Game_running_flag=0;
            }
        }
        else
        {
            stbt.setEnabled(true);
            refresh.setEnabled(false);
        }
        lab.setIcon(new javax.swing.ImageIcon("img\\lav 6\\first.jpg"));
        re_useable();
    }//GEN-LAST:event_refreshActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        if(EB[0]!=0)
        {
            int no=1;
            for(int i=0;i<12;i++)
            {
                if(Rname[i].equals("Jackfruits") && EB[0]==1)
                {
                    bt_color("Jackfruits");
                    score+=2500;
                    EB[0]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        if(EB[1]!=0)
        {
            int no=1;
            for(int i=0;i<12;i++)
            {
                if(Rname[i].equals("Passion fruit") && EB[1]==1)
                {
                    bt_color("Passion fruit");
                    score+=2500;
                    EB[1]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        if(EB[2]!=0)
        {
            int no=1;
            for(int i=0;i<12;i++)
            {
                if(Rname[i].equals("Feijoa") && EB[2]==1)
                {
                    bt_color("Feijoa");
                    score+=2500;
                    EB[2]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        if(EB[3]!=0)
        {
            int no=1;
            for(int i=0;i<12;i++)
            {
                if(Rname[i].equals("Dragon fruit") && EB[3]==1)
                {
                    bt_color("Dragon fruit");
                    score+=2500;
                    EB[3]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        if(EB[4]!=0)
        {
            int no=1;
            for(int i=0;i<12;i++)
            {
                if(Rname[i].equals("Strawberry") && EB[4]==1)
                {
                    bt_color("Strawberry");
                    score+=2500;
                    EB[4]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        if(EB[5]!=0)
        {
            int no=1;
            for(int i=0;i<12;i++)
            {
                if(Rname[i].equals("Lychee") && EB[5]==1)
                {
                    bt_color("Lychee");
                    score+=2500;
                    EB[5]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        if(EB[6]!=0)
        {
            int no=1;
            for(int i=0;i<12;i++)
            {
                if(Rname[i].equals("Satsuma") && EB[6]==1)
                {
                    bt_color("Satsuma");
                    score+=2500;
                    EB[6]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        if(EB[7]!=0)
        {
            int no=1;
            for(int i=0;i<12;i++)
            {
                if(Rname[i].equals("Pineappl") && EB[7]==1)
                {
                    bt_color("Pineappl");
                    score+=2500;
                    EB[7]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        if(EB[8]!=0)
        {
            int no=1;
            for(int i=0;i<12;i++)
            {
                if(Rname[i].equals("Peer") && EB[8]==1)
                {
                    bt_color("Peer");
                    score+=2500;
                    EB[8]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        if(EB[9]!=0)
        {
            int no=1;
            for(int i=0;i<12;i++)
            {
                if(Rname[i].equals("Graps") && EB[9]==1)
                {
                    bt_color("Graps");
                    score+=2500;
                    EB[9]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        if(EB[10]!=0)
        {
            int no=1;
            for(int i=0;i<12;i++)
            {
                if(Rname[i].equals("Banana") && EB[10]==1)
                {
                    bt_color("Banana");
                    score+=2500;
                    EB[10]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        if(EB[11]!=0)
        {
            int no=1;
            for(int i=0;i<12;i++)
            {
                if(Rname[i].equals("Guava") && EB[11]==1)
                {
                    bt_color("Guava");
                    score+=2500;
                    EB[11]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        if(EB[12]!=0)
        {
            int no=1;
            for(int i=0;i<12;i++)
            {
                if(Rname[i].equals("Galia melon") && EB[12]==1)
                {
                    bt_color("Galia melon");
                    score+=2500;
                    EB[12]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        if(EB[13]!=0)
        {
            int no=1;
            for(int i=0;i<12;i++)
            {
                if(Rname[i].equals("Water melon") && EB[13]==1)
                {
                    bt_color("Water melon");
                    score+=2500;
                    EB[13]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        if(EB[14]!=0)
        {
            int no=1;
            for(int i=0;i<12;i++)
            {
                if(Rname[i].equals("Rambutan") && EB[14]==1)
                {
                    bt_color("Rambutan");
                    score+=2500;
                    EB[14]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        if(EB[15]!=0)
        {
            int no=1;
            for(int i=0;i<12;i++)
            {
                if(Rname[i].equals("Watermelon slice") && EB[15]==1)
                {
                    bt_color("Watermelon slice");
                    score+=2500;
                    EB[15]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // JOptionPane.showMessageDialog(null, "bC");
        if(EB[16]!=0)
        {
            int no=1;
            for(int i=0;i<12;i++)
            {
                if(Rname[i].equals("Mango") && EB[16]==1)
                {
                    bt_color("Mango");
                    score+=2500;
                    EB[16]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        //    JOptionPane.showMessageDialog(null, "bC");
        if(EB[17]!=0)
        {
            int no=1;
            for(int i=0;i<12;i++)
            {
                if(Rname[i].equals("Coconut") && EB[17]==1)
                {
                    bt_color("Coconut");
                    score+=2500;
                    EB[17]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        //JOptionPane.showMessageDialog(null, "bC");
        if(EB[18]!=0)
        {
            int no=1;
            for(int i=0;i<12;i++)
            {
                if(Rname[i].equals("Blackberry") && EB[18]==1)
                {
                    bt_color("Blackberry");
                    score+=2500;
                    EB[18]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        if(EB[19]!=0)
        {
            int no=1;
            for(int i=0;i<12;i++)
            {
                if(Rname[i].equals("Tangerines") && EB[19]==1)
                {
                    bt_color("Tangerines");
                    score+=2500;
                    EB[19]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        if(EB[20]!=0)
        {
            int no=1;
            for(int i=0;i<12;i++)
            {
                if(Rname[i].equals("Cherry") && EB[20]==1)
                {
                    bt_color("Cherry");
                    score+=2500;
                    EB[20]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        if(EB[21]!=0)
        {
            int no=1;
            for(int i=0;i<12;i++)
            {
                if(Rname[i].equals("Orange Slice") && EB[21]==1)
                {
                    bt_color("Orange Slice");
                    score+=2500;
                    EB[21]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel23MouseClicked

    private void stbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stbtActionPerformed
        int opt=JOptionPane.showConfirmDialog(this, "Are you Ready?", "Select One", JOptionPane.YES_NO_OPTION);
        if(opt==0)
        {
            lab.setIcon(new javax.swing.ImageIcon("img\\lav 6\\lav6.png"));
            stbt.setEnabled(false);
            refresh.setEnabled(true);
            refresh.setText("Abandon");
            button_flag=1;
            Game_running_flag=1;
            src.setText("0");
            //setPIC();
            make_one();
            Random rg = new Random();
            int[] ar=new int[28];

            for(int i=0;i<28;i++)
            ar[i]=-1;
            int co=0,flag=0;

            for (int idx = 0;; ++idx)
            {
                int n = rg.nextInt(27);
                if(ar[n]==-1)
                {
                    if(co>=12)
                    {
                        flag=1;
                        break;
                    }
                    br[co++]=n;
                    ar[n]=-5;

                }
                if(flag==1)
                break;
            }
            for(int p=0;p<12;p++)
            {
                Rname[p]=fname[br[p]];
            }
            set_name();
            result=0;
            stop=0;
            Thread finish;
            finish v=new finish();
            v.start();
            Thread Stopwatch;
            Stopwatch vv=new Stopwatch();
            vv.start();
        }
    }//GEN-LAST:event_stbtActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    dead=1;
    cp.stop();
    }//GEN-LAST:event_formWindowClosing

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
    if(EB[22]!=0)
        {
            int no=1;
            for(int i=0;i<12;i++)
            {
                if(Rname[i].equals("Lime") && EB[22]==1)
                {
                    bt_color("Lime");
                    score+=2500;
                    EB[22]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
    if(EB[23]!=0)
        {
            int no=1;
            for(int i=0;i<12;i++)
            {
                if(Rname[i].equals("Fig") && EB[23]==1)
                {
                    bt_color("Fig");
                    score+=2500;
                    EB[23]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
    if(EB[24]!=0)
        {
            int no=1;
            for(int i=0;i<12;i++)
            {
                if(Rname[i].equals("Honeydew melon") && EB[24]==1)
                {
                    bt_color("Honeydew melon");
                    score+=2500;
                    EB[24]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
    if(EB[25]!=0)
        {
            int no=1;
            for(int i=0;i<12;i++)
            {
                if(Rname[i].equals("Raspberry") && EB[25]==1)
                {
                    bt_color("Raspberry");
                    score+=2500;
                    EB[25]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
    if(EB[26]!=0)
        {
            int no=1;
            for(int i=0;i<12;i++)
            {
                if(Rname[i].equals("Blackcurrant") && EB[26]==1)
                {
                    bt_color("Blackcurrant");
                    score+=2500;
                    EB[26]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
    if(EB[27]!=0)
        {
            int no=1;
            for(int i=0;i<12;i++)
            {
                if(Rname[i].equals("Loquat") && EB[27]==1)
                {
                    bt_color("Loquat");
                    score+=2500;
                    EB[27]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel29MouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Level_Six.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Level_Six.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Level_Six.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Level_Six.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                Level_Six dialog = new Level_Six(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b10;
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lab;
    private javax.swing.JLabel lf;
    private javax.swing.JLabel p_lavel_value;
    private javax.swing.JProgressBar pbar;
    private javax.swing.JButton refresh;
    private javax.swing.JLabel src;
    private javax.swing.JButton stbt;
    private javax.swing.JLabel timeP;
    // End of variables declaration//GEN-END:variables

private int dead=0;
private int Game_running_flag=0;
private int button_flag=0;
int[] br=new int[12];

public void make_zero()
    {
        for(int i=0;i<EB.length;i++)
        {
            EB[i]=0;
        }
    }
    public void make_one()
    {
        for(int i=0;i<EB.length;i++)
        {
            EB[i]=1;
        }
    }

// start thread part
private void bt_color(String ss) {
    if(b1.getText().equalsIgnoreCase(ss))
    {
        b1.setBackground(Color.BLACK);
        b1.setForeground(Color.GRAY);
    }
    else if(b2.getText().equalsIgnoreCase(ss))
    {
        b2.setBackground(Color.BLACK);
        b2.setForeground(Color.GRAY);
    }
    else if(b3.getText().equalsIgnoreCase(ss))
    {
        b3.setBackground(Color.BLACK);
        b3.setForeground(Color.GRAY);
    }
    else if(b4.getText().equalsIgnoreCase(ss))
    {
        b4.setBackground(Color.BLACK);
        b4.setForeground(Color.GRAY);
    }
    else if(b5.getText().equalsIgnoreCase(ss))
    {
        b5.setBackground(Color.BLACK);
        b5.setForeground(Color.GRAY);
    }
    else if(b6.getText().equalsIgnoreCase(ss))
    {
        b6.setBackground(Color.BLACK);
        b6.setForeground(Color.GRAY);
    }
    else if(b7.getText().equalsIgnoreCase(ss))
    {
        b7.setBackground(Color.BLACK);
        b7.setForeground(Color.GRAY);
    }
    else if(b8.getText().equalsIgnoreCase(ss))
    {
        b8.setBackground(Color.BLACK);
        b8.setForeground(Color.GRAY);
    }
    else if(b9.getText().equalsIgnoreCase(ss))
    {
        b9.setBackground(Color.BLACK);
        b9.setForeground(Color.GRAY);
    }
    else if(b10.getText().equalsIgnoreCase(ss))
    {
        b10.setBackground(Color.BLACK);
        b10.setForeground(Color.GRAY);
    }
    else if(b11.getText().equalsIgnoreCase(ss))
    {
        b11.setBackground(Color.BLACK);
        b11.setForeground(Color.GRAY);
    }
    else if(b12.getText().equalsIgnoreCase(ss))
    {
        b12.setBackground(Color.BLACK);
        b12.setForeground(Color.GRAY);
    }
}
private void bt_color_nill() {
    b1.setBackground(null);
    b1.setForeground(null);
    b2.setBackground(null);
    b2.setForeground(null);
    b3.setBackground(null);
    b3.setForeground(null);
    b4.setBackground(null);
    b4.setForeground(null);
    b5.setBackground(null);
    b5.setForeground(null);
    b6.setBackground(null);
    b6.setForeground(null);
    b7.setBackground(null);
    b7.setForeground(null);
    b8.setBackground(null);
    b8.setForeground(null);
    b9.setBackground(null);
    b9.setForeground(null);
    b10.setBackground(null);
    b10.setForeground(null);
    b11.setBackground(null);
    b11.setForeground(null);
    b12.setBackground(null);
    b12.setForeground(null);
}
    private void nill() {
    bt_color_nill();
    b1.setText(null);
    b2.setText(null);
    b3.setText(null);
    b4.setText(null);
    b5.setText(null);
    b6.setText(null);
    b8.setText(null);
    b9.setText(null);
    b10.setText(null);
    b11.setText(null);
    b7.setText(null);
    b12.setText(null);
    }
    public void set_name()
    {
            b1.setText(fname[br[0]]);
            b2.setText(fname[br[1]]);
            b3.setText(fname[br[2]]);
            b4.setText(fname[br[3]]);
            b5.setText(fname[br[4]]);
            b6.setText(fname[br[5]]);
            b7.setText(fname[br[6]]);
            b8.setText(fname[br[7]]);
            b9.setText(fname[br[8]]);
            b10.setText(fname[br[9]]);
            b11.setText(fname[br[10]]);
            b12.setText(fname[br[11]]);
    }
public void set_pbar()
{
    pbar.setValue(database_con.process_value("lav6"));
    p_lavel_value.setText(String.valueOf(pbar.getValue())+"%");
}
public void re_useable()
{
    make_zero();
        score=0;
        err=0;
        result=0;
        stop=1;
       // src.setText(String.valueOf(score));
      //  timeP.setText("0");
        nill();
      //  lf.setText("0");
        set_pbar();
}
class finish extends Thread{
      
      public void run(){
      while(true){
          lf.setText(String.valueOf(3-(err-result)));
      if(result==12)
      {
          lab.setIcon(new javax.swing.ImageIcon("img\\lav 6\\first.jpg"));
              try {
                  int tm=k;
                  stop=1;
                  int points;
                  Game_running_flag=0;
                  int life=Integer.parseInt(lf.getText());
                  points=score+(life*2500)+((60-k)*1000);               
                  src.setText(String.valueOf(score));
                  database_con.update_score("lav6", points);
                  database_con.update_time("lav6", k);
                  if(database_con.get_others("lav6")==0)
                  {
                     // System.out.print("one");
                     pbar.setValue(pbar.getValue()+(life*2)); 
                     p_lavel_value.setText(String.valueOf(pbar.getValue())+"%");
                     int temp=(int)pbar.getValue()/100;
                     String sql="UPDATE info SET process= "+pbar.getValue()+", others= "+temp+" WHERE name='lav6'";
                     Connection con=database_con.db_check();
                     PreparedStatement st=con.prepareStatement(sql);
                     st.executeUpdate();
                  }   
                  ScoreCounter dialog = new ScoreCounter(new javax.swing.JFrame(), true,score,life,(60-k));
                  dialog.setVisible(true);
                  if(database_con.get_others("lav6")==1)
                  {
//                      try {
//                          FileReadWrite.FileInput(1, "6th");
//                          FileReadWrite.FileInput(1, "flag");
//                      } catch (IOException ex) {
//                          Logger.getLogger(Level_One.class.getName()).log(Level.SEVERE, null, ex);
//                      }
                      Master n = new Master(new javax.swing.JFrame(), true);
                      n.setVisible(true);
                     String sql="UPDATE info SET others= 2 WHERE name='lav6'";
                     Connection con=database_con.db_check();
                     PreparedStatement st=con.prepareStatement(sql);
                     st.executeUpdate();
                  }
                  database_con.Won_count("lav6");
                  nill();
                  refresh.setEnabled(false);
                  stbt.setEnabled(true);
                  //JOptionPane.showMessageDialog(null, "Screen clear !\n now Tottal Score:"+score);
                  re_useable();
                  this.suspend();
              } catch (SQLException ex) {
                  Logger.getLogger(Level_One.class.getName()).log(Level.SEVERE, null, ex);
              }
      }
      if(k>60)
      {
          lab.setIcon(new javax.swing.ImageIcon("img\\lav 6\\first.jpg"));
          stop=1;
          Game_running_flag=0;
          database_con.Loss_count("lav6");
          nill();
          refresh.setEnabled(false);
          stbt.setEnabled(true);
          TimeOver dialog = new TimeOver(new javax.swing.JFrame(), true);
          dialog.setVisible(true);
          k=0;
          re_useable();
          this.suspend();
          
      }
      if(err-result>=3)
      {
          lab.setIcon(new javax.swing.ImageIcon("img\\lav 6\\first.jpg"));
          stop=1;
          Game_running_flag=0;
          database_con.Loss_count("lav6");
          nill();
          lf.setText("0");
          stbt.setEnabled(true);
          refresh.setEnabled(false);
          GameOver dialog = new GameOver(new javax.swing.JFrame(), true);
          dialog.setVisible(true);
          k=0;
          re_useable();
          this.suspend();
         
      }
      if(dead==1)
      {
          this.suspend();
      }
      }
      }
}

class Stopwatch extends Thread{
      
      public void run(){
          Clip hoverActive=SoundPlay.play("beep.wav");
   for(k=0;;k++)
      {
              try
              {
               
               Thread.sleep(1000); 
               timeP.setText(String.valueOf(k));
               if(stop==1)
               {
                   hoverActive.stop();
                   this.suspend();
                   timeP.setText("0");
               }
               if (k==55)
               {
                   
                   hoverActive.start();
                   hoverActive.loop(40);
               }
               }
               catch (InterruptedException ie)
               {  
               }
        }
  }
}

//end thread part
//end manin tag


}
