/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Jframe;

import all_classes.FileReadWrite;
import all_classes.SoundPlay;
import all_classes.database_con;
import java.awt.Color;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.Clip;
import javax.sound.sampled.FloatControl;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author CETC
 */
public class Level_Two extends javax.swing.JDialog {

    /**
     * Creates new form Level_two
     */
    int result;
    int snd=0;
    int stop;
    String fname[]={"Apricot","Black currant", "Coconut", "Coconut’s water",
                    "Dragon fruit", "Peach", "Feijoa", "Fig", "Galia melon", "Lychee", "Tangerines", 
                    "Star fruit", "Raspberry", "Papaya", "Quince", "Pineapple", "Plum", "Peer" , "Fruit sticker"};
    String[] Rname=new String[5];
    private int score;
    int tm=0;
    int k;
    int err=0;
    int[] EB=new int[19];
    Clip cp=SoundPlay.play("2nd.wav");
    public Level_Two(java.awt.Frame parent, boolean modal,int OFF_ON) {
        super(parent, modal);
        initComponents();
        ImageIcon img=new ImageIcon("img\\icon\\2nd.png");
        this.setIconImage(img.getImage());
        lab.setIcon(new javax.swing.ImageIcon("img\\lav 2\\first.jpg"));
        make_zero();
        set_pbar();
        refresh.setEnabled(false);
        if(OFF_ON==1)
        {
            cp.start();
            cp.loop(Clip.LOOP_CONTINUOUSLY);
            FloatControl gainControl = (FloatControl) cp.getControl(FloatControl.Type.MASTER_GAIN);
            gainControl.setValue(-10.0f);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stbt = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lf = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        pbar = new javax.swing.JProgressBar();
        p_lavel_value = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        timeP = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        b1 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lab = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        src = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Level 2");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        stbt.setText("Start");
        stbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stbtActionPerformed(evt);
            }
        });

        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Remaining life", 0, 0, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(51, 204, 255))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(0, 204, 255));

        lf.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lf.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lf.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lf, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lf, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Level Processing", 0, 0, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(102, 153, 255))); // NOI18N

        p_lavel_value.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Total process:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pbar, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p_lavel_value, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(pbar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p_lavel_value, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Time", 0, 0, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(153, 153, 255))); // NOI18N

        timeP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        timeP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        timeP.setText("0");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(timeP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(timeP, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(259, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel1.setLayout(null);

        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 10, 40, 40);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(390, 90, 100, 100);

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(570, 350, 30, 30);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(500, 340, 50, 60);

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 400, 20, 40);

        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6);
        jLabel6.setBounds(110, 360, 30, 40);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 190, 140, 20);

        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8);
        jLabel8.setBounds(210, 110, 30, 50);

        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9);
        jLabel9.setBounds(210, 180, 30, 40);

        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10);
        jLabel10.setBounds(250, 70, 30, 40);

        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11);
        jLabel11.setBounds(440, 240, 40, 30);

        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel13);
        jLabel13.setBounds(370, 240, 40, 30);

        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel14);
        jLabel14.setBounds(260, 260, 50, 40);

        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel15);
        jLabel15.setBounds(350, 280, 40, 30);

        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel16);
        jLabel16.setBounds(250, 330, 20, 40);

        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel17);
        jLabel17.setBounds(280, 340, 20, 30);

        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel18);
        jLabel18.setBounds(90, 70, 50, 50);

        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel19);
        jLabel19.setBounds(100, 250, 20, 30);

        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel20);
        jLabel20.setBounds(50, 330, 30, 30);

        lab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lab);
        lab.setBounds(0, 0, 610, 450);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Points", 0, 0, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(51, 153, 255))); // NOI18N

        src.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        src.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        src.setText("0");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(src, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(src, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(stbt, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(refresh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stbt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        dead=1;
        cp.stop();
    }//GEN-LAST:event_formWindowClosing

    private void stbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stbtActionPerformed
        int opt=JOptionPane.showConfirmDialog(this, "Are you Ready?", "Select One", JOptionPane.YES_NO_OPTION);
        if(opt==0)
        {
            lab.setIcon(new javax.swing.ImageIcon("img\\lav 2\\lav2.png"));
            stbt.setEnabled(false);
            refresh.setEnabled(true);
            refresh.setText("Abandon");
            button_flag=1;
            Game_running_flag=1;
            src.setText("0");
            //setPIC();
            make_one();
            Random rg = new Random();
            int[] ar=new int[19];

            for(int i=0;i<19;i++)
            ar[i]=-1;
            int co=0,flag=0;

            for (int idx = 0;; ++idx)
            {
                int n = rg.nextInt(18);
                if(ar[n]==-1)
                {
                    if(co>=5)
                    {
                        flag=1;
                        break;
                    }
                    br[co++]=n;
                    ar[n]=-5;

                }
                if(flag==1)
                break;
            }
            for(int p=0;p<5;p++)
            {
                Rname[p]=fname[br[p]];
            }
            set_name();
            result=0;
            stop=0;
            Thread finish;
            finish v=new finish();
            v.start();
            Thread Stopwatch;
            Stopwatch vv=new Stopwatch();
            vv.start();
        }
    }//GEN-LAST:event_stbtActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        if(refresh.getText().equalsIgnoreCase("Abandon"))
        {
            refresh.setText("Refresh");
            if(Game_running_flag==1)
            {
                database_con.Abandon_count("lav2");
                Game_running_flag=0;
            }
        }
        else
        {
            stbt.setEnabled(true);
            refresh.setEnabled(false);
        }
        lab.setIcon(new javax.swing.ImageIcon("img\\lav 2\\first.jpg"));
        re_useable();
    }//GEN-LAST:event_refreshActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        if(EB[9]!=0)
        {
            int no=1;
            for(int i=0;i<5;i++)
            {
                if(Rname[i].equals("Coconut’s water") && EB[9]==1)
                {
                    bt_color("Coconut’s water");
                    score+=2500;
                    EB[9]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
    if(EB[0]!=0)
        {
            int no=1;
            for(int i=0;i<5;i++)
            {
                if(Rname[i].equals("Peach") && EB[0]==1)
                {
                    bt_color("Peach");
                    score+=2500;
                    EB[0]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
    if(EB[1]!=0)
        {
            int no=1;
            for(int i=0;i<5;i++)
            {
                if(Rname[i].equals("Raspberry") && EB[1]==1)
                {
                    bt_color("Raspberry");
                    score+=2500;
                    EB[1]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
    if(EB[2]!=0)
        {
            int no=1;
            for(int i=0;i<5;i++)
            {
                if(Rname[i].equals("Tangerines") && EB[2]==1)
                {
                    bt_color("Tangerines");
                    score+=2500;
                    EB[2]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
    if(EB[3]!=0)
        {
            int no=1;
            for(int i=0;i<5;i++)
            {
                if(Rname[i].equals("Apricot") && EB[3]==1)
                {
                    bt_color("Apricot");
                    score+=2500;
                    EB[3]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
    if(EB[4]!=0)
        {
            int no=1;
            for(int i=0;i<5;i++)
            {
                if(Rname[i].equals("Plum") && EB[4]==1)
                {
                    bt_color("Plum");
                    score+=2500;
                    EB[4]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
    if(EB[5]!=0)
        {
            int no=1;
            for(int i=0;i<5;i++)
            {
                if(Rname[i].equals("Fig") && EB[5]==1)
                {
                    bt_color("Fig");
                    score+=2500;
                    EB[5]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
    if(EB[6]!=0)
        {
            int no=1;
            for(int i=0;i<5;i++)
            {
                if(Rname[i].equals("Fruit sticker") && EB[6]==1)
                {
                    bt_color("Fruit sticker");
                    score+=2500;
                    EB[6]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
    if(EB[7]!=0)
        {
            int no=1;
            for(int i=0;i<5;i++)
            {
                if(Rname[i].equals("Papaya") && EB[7]==1)
                {
                    bt_color("Papaya");
                    score+=2500;
                    EB[7]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
    if(EB[8]!=0)
        {
            int no=1;
            for(int i=0;i<5;i++)
            {
                if(Rname[i].equals("Pineapple") && EB[8]==1)
                {
                    bt_color("Pineapple");
                    score+=2500;
                    EB[8]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
    if(EB[10]!=0)
        {
            int no=1;
            for(int i=0;i<5;i++)
            {
                if(Rname[i].equals("Dragon fruit") && EB[10]==1)
                {
                    bt_color("Dragon fruit");
                    score+=2500;
                    EB[10]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
    if(EB[11]!=0)
        {
            int no=1;
            for(int i=0;i<5;i++)
            {
                if(Rname[i].equals("Lychee") && EB[11]==1)
                {
                    bt_color("Lychee");
                    score+=2500;
                    EB[11]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
    if(EB[12]!=0)
        {
            int no=1;
            for(int i=0;i<5;i++)
            {
                if(Rname[i].equals("Quince") && EB[12]==1)
                {
                    bt_color("Quince");
                    score+=2500;
                    EB[12]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
    if(EB[13]!=0)
        {
            int no=1;
            for(int i=0;i<5;i++)
            {
                if(Rname[i].equals("Galia melon") && EB[13]==1)
                {
                    bt_color("Galia melon");
                    score+=2500;
                    EB[13]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
    if(EB[14]!=0)
        {
            int no=1;
            for(int i=0;i<5;i++)
            {
                if(Rname[i].equals("Coconut") && EB[14]==1)
                {
                    bt_color("Coconut");
                    score+=2500;
                    EB[14]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
    if(EB[15]!=0)
        {
            int no=1;
            for(int i=0;i<5;i++)
            {
                if(Rname[i].equals("Peer") && EB[15]==1)
                {
                    bt_color("Peer");
                    score+=2500;
                    EB[15]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
   // JOptionPane.showMessageDialog(null, "bC");
        if(EB[16]!=0)
        {
            int no=1;
            for(int i=0;i<5;i++)
            {
                if(Rname[i].equals("Black currant") && EB[16]==1)
                {
                    bt_color("Black currant");
                    score+=2500;
                    EB[16]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
//    JOptionPane.showMessageDialog(null, "bC");
        if(EB[17]!=0)
        {
            int no=1;
            for(int i=0;i<5;i++)
            {
                if(Rname[i].equals("Star fruit") && EB[17]==1)
                {
                    bt_color("Star fruit");
                    score+=2500;
                    EB[17]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
//JOptionPane.showMessageDialog(null, "bC");
        if(EB[18]!=0)
        {
            int no=1;
            for(int i=0;i<5;i++)
            {
                if(Rname[i].equals("Feijoa") && EB[18]==1)
                {
                    bt_color("Feijoa");
                    score+=2500;
                    EB[18]=2;
                    src.setText(String.valueOf(score));
                    result++;
                    SoundPlay.ok();
                    no=0;
                }
            }
            if(no==1)
            SoundPlay.no();
            err++;
        }
    }//GEN-LAST:event_jLabel20MouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Level_Two.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Level_Two.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Level_Two.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Level_Two.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                Level_Two dialog = new Level_Two(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lab;
    private javax.swing.JLabel lf;
    private javax.swing.JLabel p_lavel_value;
    private javax.swing.JProgressBar pbar;
    private javax.swing.JButton refresh;
    private javax.swing.JLabel src;
    private javax.swing.JButton stbt;
    private javax.swing.JLabel timeP;
    // End of variables declaration//GEN-END:variables
private int dead=0;
private int Game_running_flag=0;
private int button_flag=0;
int[] br=new int[5];

public void make_zero()
    {
        for(int i=0;i<EB.length;i++)
        {
            EB[i]=0;
        }
    }
    public void make_one()
    {
        for(int i=0;i<EB.length;i++)
        {
            EB[i]=1;
        }
    }

// start thread part
private void bt_color(String ss) {
    if(b1.getText().equalsIgnoreCase(ss))
    {
        b1.setBackground(Color.BLACK);
        b1.setForeground(Color.GRAY);
    }
    else if(b2.getText().equalsIgnoreCase(ss))
    {
        b2.setBackground(Color.BLACK);
        b2.setForeground(Color.GRAY);
    }
    else if(b3.getText().equalsIgnoreCase(ss))
    {
        b3.setBackground(Color.BLACK);
        b3.setForeground(Color.GRAY);
    }
    else if(b4.getText().equalsIgnoreCase(ss))
    {
        b4.setBackground(Color.BLACK);
        b4.setForeground(Color.GRAY);
    }
    else if(b5.getText().equalsIgnoreCase(ss))
    {
        b5.setBackground(Color.BLACK);
        b5.setForeground(Color.GRAY);
    }
}
private void bt_color_nill() {
    b1.setBackground(null);
    b1.setForeground(null);
    b2.setBackground(null);
    b2.setForeground(null);
    b3.setBackground(null);
    b3.setForeground(null);
    b4.setBackground(null);
    b4.setForeground(null);
    b5.setBackground(null);
    b5.setForeground(null);
}
    private void nill() {
    bt_color_nill();
    b1.setText(null);
    b2.setText(null);
    b3.setText(null);
    b4.setText(null);
    b5.setText(null);
    }
    public void set_name()
    {
            b1.setText(fname[br[0]]);
            b2.setText(fname[br[1]]);
            b3.setText(fname[br[2]]);
            b4.setText(fname[br[3]]);
            b5.setText(fname[br[4]]);
    }
public void set_pbar()
{
    pbar.setValue(database_con.process_value("lav2"));
    p_lavel_value.setText(String.valueOf(pbar.getValue())+"%");
}
public void re_useable()
{
    make_zero();
        score=0;
        err=0;
        result=0;
        stop=1;
       // src.setText(String.valueOf(score));
      //  timeP.setText("0");
        nill();
      //  lf.setText("0");
        set_pbar();
}
class finish extends Thread{
      
      public void run(){
      while(true){
          lf.setText(String.valueOf(3-(err-result)));
      if(result==5)
      {
          lab.setIcon(new javax.swing.ImageIcon("img\\lav 2\\first.jpg"));
              try {
                  int tm=k;
                  stop=1;
                  int points;
                  Game_running_flag=0;
                  int life=Integer.parseInt(lf.getText());
                  points=score+(life*2500)+((30-k)*1000);               
                  src.setText(String.valueOf(score));
                  database_con.update_score("lav2", points);
                  database_con.update_time("lav2", k);
                  if(database_con.get_others("lav2")==0)
                  {
                     // System.out.print("one");
                     pbar.setValue(pbar.getValue()+(life*2)); 
                     p_lavel_value.setText(String.valueOf(pbar.getValue())+"%");
                     int temp=(int)pbar.getValue()/100;
                     String sql="UPDATE info SET process= "+pbar.getValue()+", others= "+temp+" WHERE name='lav2'";
                     Connection con=database_con.db_check();
                     PreparedStatement st=con.prepareStatement(sql);
                     st.executeUpdate();
                  }   
                  ScoreCounter dialog = new ScoreCounter(new javax.swing.JFrame(), true,score,life,(30-k));
                  dialog.setVisible(true);
                  if(database_con.get_others("lav2")==1)
                  {
                      try {
                          FileReadWrite.FileInput(1, "3rd");
                          FileReadWrite.FileInput(1, "flag");
                      } catch (IOException ex) {
                          Logger.getLogger(Level_One.class.getName()).log(Level.SEVERE, null, ex);
                      }
                      Congratulate n = new Congratulate(new javax.swing.JFrame(), true);
                      n.setVisible(true);
                     String sql="UPDATE info SET others= 2 WHERE name='lav2'";
                     Connection con=database_con.db_check();
                     PreparedStatement st=con.prepareStatement(sql);
                     st.executeUpdate();
                  }
                  database_con.Won_count("lav2");
                  nill();
                  refresh.setEnabled(false);
                  stbt.setEnabled(true);
                  //JOptionPane.showMessageDialog(null, "Screen clear !\n now Tottal Score:"+score);
                  re_useable();
                  this.suspend();
              } catch (SQLException ex) {
                  Logger.getLogger(Level_One.class.getName()).log(Level.SEVERE, null, ex);
              }
      }
      if(k>30)
      {
          lab.setIcon(new javax.swing.ImageIcon("img\\lav 2\\first.jpg"));
          stop=1;
          Game_running_flag=0;
          database_con.Loss_count("lav2");
          nill();
          refresh.setEnabled(false);
          stbt.setEnabled(true);
          TimeOver dialog = new TimeOver(new javax.swing.JFrame(), true);
          dialog.setVisible(true);
          k=0;
          re_useable();
          this.suspend();
          
      }
      if(err-result>=3)
      {
          lab.setIcon(new javax.swing.ImageIcon("img\\lav 2\\first.jpg"));
          stop=1;
          Game_running_flag=0;
          database_con.Loss_count("lav2");
          nill();
          lf.setText("0");
          stbt.setEnabled(true);
          refresh.setEnabled(false);
          GameOver dialog = new GameOver(new javax.swing.JFrame(), true);
          dialog.setVisible(true);
          k=0;
          re_useable();
          this.suspend();
         
      }
      if(dead==1)
      {
          this.suspend();
      }
      }
      }
}

class Stopwatch extends Thread{
      
      public void run(){
          Clip hoverActive=SoundPlay.play("beep.wav");
   for(k=0;;k++)
      {
              try
              {
               
               Thread.sleep(1000); 
               timeP.setText(String.valueOf(k));
               if(stop==1)
               {
                   hoverActive.stop();
                   this.suspend();
                   timeP.setText("0");
               }
               if (k==25)
               {
                   
                   hoverActive.start();
                   hoverActive.loop(40);
               }
               }
               catch (InterruptedException ie)
               {  
               }
        }
  }
}

//end thread part
//end manin tag

}
