package Jframe;


import all_classes.database_con;
import java.awt.Toolkit;
import java.sql.Connection;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author CETC
 */
public class MainP extends javax.swing.JFrame {

    /**
     * Creates new form MainP
     */
    Connection con=null;
    int result;
    int snd=0;
    int stop;
    String fname[]={"Apple", "Quince", "Pomelos", "Orange", "Avocado", "Green mango", "Pomegranate", "Jackfruits", "Blackgrapes", "Loquat", "Strawberry", "Feijoa", "Passionfruit", "Lemon", "Satsuma","Kumquat","Date","Cherry","Pineapple","Kiwi fruit","Rambutan","Jujube","Starfruit","Guava","Lichi"};
    String[] Rname=new String[8];
    int score=0;
    int tm=0;
    int k;
    int err=0;
    public MainP() {
        
        initComponents();
        ImageIcon img=new ImageIcon("img\\icon\\3rd.png");
        this.setIconImage(img.getImage());
        int pp=20;
        pbar.setValue(pp);
        p_lavel_value.setText(p_lavel_value.getText()+String.valueOf(pp)+" %");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpp = new javax.swing.JPanel();
        mainp = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        b11 = new javax.swing.JButton();
        b12 = new javax.swing.JButton();
        b13 = new javax.swing.JButton();
        b14 = new javax.swing.JButton();
        b15 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        b16 = new javax.swing.JButton();
        b17 = new javax.swing.JButton();
        b18 = new javax.swing.JButton();
        b19 = new javax.swing.JButton();
        b20 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        b21 = new javax.swing.JButton();
        b22 = new javax.swing.JButton();
        b23 = new javax.swing.JButton();
        b24 = new javax.swing.JButton();
        b25 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        l1 = new javax.swing.JButton();
        l2 = new javax.swing.JButton();
        l5 = new javax.swing.JButton();
        l6 = new javax.swing.JButton();
        l7 = new javax.swing.JButton();
        l8 = new javax.swing.JButton();
        stbt = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        src = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        timeP = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        pbar = new javax.swing.JProgressBar();
        p_lavel_value = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fruits Finding");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        jPanel2.add(b6);

        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        jPanel2.add(b7);

        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        jPanel2.add(b8);

        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        jPanel2.add(b9);

        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });
        jPanel2.add(b10);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });
        jPanel3.add(b11);

        b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b12ActionPerformed(evt);
            }
        });
        jPanel3.add(b12);

        b13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b13ActionPerformed(evt);
            }
        });
        jPanel3.add(b13);

        b14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b14ActionPerformed(evt);
            }
        });
        jPanel3.add(b14);

        b15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b15ActionPerformed(evt);
            }
        });
        jPanel3.add(b15);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        b16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b16ActionPerformed(evt);
            }
        });
        jPanel4.add(b16);

        b17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b17ActionPerformed(evt);
            }
        });
        jPanel4.add(b17);

        b18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b18ActionPerformed(evt);
            }
        });
        jPanel4.add(b18);

        b19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b19ActionPerformed(evt);
            }
        });
        jPanel4.add(b19);

        b20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b20ActionPerformed(evt);
            }
        });
        jPanel4.add(b20);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        b21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b21ActionPerformed(evt);
            }
        });
        jPanel5.add(b21);

        b22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b22ActionPerformed(evt);
            }
        });
        jPanel5.add(b22);

        b23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b23ActionPerformed(evt);
            }
        });
        jPanel5.add(b23);

        b24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b24ActionPerformed(evt);
            }
        });
        jPanel5.add(b24);

        b25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b25ActionPerformed(evt);
            }
        });
        jPanel5.add(b25);

        javax.swing.GroupLayout mainpLayout = new javax.swing.GroupLayout(mainp);
        mainp.setLayout(mainpLayout);
        mainpLayout.setHorizontalGroup(
            mainpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        mainpLayout.setVerticalGroup(
            mainpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(l1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l2, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                .addGap(72, 72, 72)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(l5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l7, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                .addGap(70, 70, 70)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l8, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(l5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(l8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        stbt.setText("Start");
        stbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stbtActionPerformed(evt);
            }
        });

        jButton10.setText("Refresh");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Score board", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18), new java.awt.Color(51, 153, 255))); // NOI18N

        src.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        src.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        src.setText("0");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(src, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(src, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Time", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(153, 153, 255))); // NOI18N

        timeP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        timeP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        timeP.setText("0");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(timeP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(timeP, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Level Processing", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(102, 153, 255))); // NOI18N

        p_lavel_value.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        p_lavel_value.setText("Total process:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(p_lavel_value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(pbar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(p_lavel_value, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainppLayout = new javax.swing.GroupLayout(mainpp);
        mainpp.setLayout(mainppLayout);
        mainppLayout.setHorizontalGroup(
            mainppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainppLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainppLayout.createSequentialGroup()
                        .addComponent(mainp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mainppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(mainppLayout.createSequentialGroup()
                                .addComponent(stbt, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mainppLayout.setVerticalGroup(
            mainppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainppLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainppLayout.createSequentialGroup()
                        .addGroup(mainppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(stbt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(mainpp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(mainpp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b14ActionPerformed
     for(int i=0;i<8;i++)
     {
         if(Rname[i].equals("Lemon"))
         {
             score+=2500;
             b14.setIcon(null);
             b14.setEnabled(false);
             src.setText(String.valueOf(score));
             result++;
         }
     }
     err++;
    }//GEN-LAST:event_b14ActionPerformed

    private void stbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stbtActionPerformed
    int opt=JOptionPane.showConfirmDialog(this, "Are you Ready?", "Select One", JOptionPane.YES_NO_OPTION);
    if(opt==0)
    {
        stbt.setEnabled(false);
        setPIC();
        Random rg = new Random();
    int[] ar=new int[25];
    for(int i=0;i<24;i++)
        ar[i]=-1;
    int co=0,flag=0;
    
    for (int idx = 0;; ++idx){
      int n = rg.nextInt(24);
      if(ar[n]==-1)
      {
          br[co++]=n;
          ar[n]=1;
          if(co>=8)
          { 
              flag=1;
              break;
          }
      }
      if(flag==1)
          break;
    }
    l1.setText(fname[br[0]]);
    l2.setText(fname[br[1]]);
    l5.setText(fname[br[2]]);
    l6.setText(fname[br[3]]);
    l7.setText(fname[br[4]]);
    l8.setText(fname[br[5]]);
    for(int p=0;p<8;p++)
    {
        Rname[p]=fname[br[p]];
    }
    result=0;
    stop=0;
    Thread finish;
    finish v=new finish();
    v.start();
    Thread Stopwatch;
    Stopwatch w=new Stopwatch();
    w.start();
    }
    }//GEN-LAST:event_stbtActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
    all_null();
    all_true();
    score=0;
    err=0;
    result=0;
    stop=1;
    src.setText(String.valueOf(score));
    timeP.setText(String.valueOf(score));
    }//GEN-LAST:event_jButton10ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
     for(int i=0;i<8;i++)
     {
         if(Rname[i].equals("Apple"))
         {
             score+=2500;
             b1.setIcon(null);
             src.setText(String.valueOf(score));
             b1.setEnabled(false);
             result++;
         }
         
     }
     err++;
    }//GEN-LAST:event_b1ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        for(int i=0;i<8;i++)
     {
         if(Rname[i].equals("Avocado"))
         {
             score+=2500;
             b5.setIcon(null);
             b5.setEnabled(false);
             src.setText(String.valueOf(score));
             result++;
         }
     }
        err++;
    }//GEN-LAST:event_b5ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
      for(int i=0;i<8;i++)
     {
         if(Rname[i].equals("Quince"))
         {
             score+=2500;
             b2.setIcon(null);
             b2.setEnabled(false);
             src.setText(String.valueOf(score));
             result++;
         }
     }
      err++;
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
     for(int i=0;i<8;i++)
     {
         if(Rname[i].equals("Pomelos"))
         {
             score+=2500;
             b3.setIcon(null);
             b3.setEnabled(false);
             src.setText(String.valueOf(score));
             result++;
         }
     }
     err++;
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
     for(int i=0;i<8;i++)
     {
         if(Rname[i].equals("Orange"))
         {
             score+=2500;
             b4.setIcon(null);
             b4.setEnabled(false);
             src.setText(String.valueOf(score));
             result++;
         }
     }
     err++;
    }//GEN-LAST:event_b4ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
      for(int i=0;i<8;i++)
     {
         if(Rname[i].equals("Green mango"))
         {
             score+=2500;
             b6.setIcon(null);
             b6.setEnabled(false);
             src.setText(String.valueOf(score));
             result++;
         }
     }
      err++;
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
     for(int i=0;i<8;i++)
     {
         if(Rname[i].equals("Pomegranate"))
         {
             score+=2500;
             b7.setIcon(null);
             b7.setEnabled(false);
             src.setText(String.valueOf(score));
             result++;
         }
     }
     err++;
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
      for(int i=0;i<8;i++)
     {
         if(Rname[i].equals("Jackfruits"))
         {
             score+=2500;
             b8.setIcon(null);
             b8.setEnabled(false);
             src.setText(String.valueOf(score));
             result++;
         }
     }
      err++;
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
     for(int i=0;i<8;i++)
     {
         if(Rname[i].equals("Blackgrapes"))
         {
             score+=2500;
             b9.setIcon(null);
             b9.setEnabled(false);
             src.setText(String.valueOf(score));
             result++;
         }
     }
     err++;
    }//GEN-LAST:event_b9ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
     for(int i=0;i<8;i++)
     {
         if(Rname[i].equals("Loquat"))
         {
             score+=2500;
             b10.setIcon(null);
             b10.setEnabled(false);
             src.setText(String.valueOf(score));
             result++;
         }
     }
     err++;
    }//GEN-LAST:event_b10ActionPerformed

    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11ActionPerformed
      for(int i=0;i<8;i++)
     {
         if(Rname[i].equals("Strawberry"))
         {
             score+=2500;
             b11.setIcon(null);
             b11.setEnabled(false);
             src.setText(String.valueOf(score));
             result++;
         }
     }
      err++;
    }//GEN-LAST:event_b11ActionPerformed

    private void b12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b12ActionPerformed
      for(int i=0;i<8;i++)
     {
         if(Rname[i].equals("Feijoa"))
         {
             score+=2500;
             b12.setIcon(null);
             b12.setEnabled(false);
             src.setText(String.valueOf(score));
             result++;
         }
     }
      err++;
    }//GEN-LAST:event_b12ActionPerformed

    private void b13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b13ActionPerformed
     for(int i=0;i<8;i++)
     {
         if(Rname[i].equals("Passionfruit"))
         {
             score+=2500;
             b13.setIcon(null);
             b13.setEnabled(false);
             src.setText(String.valueOf(score));
             result++;
         }
     }
     err++;
    }//GEN-LAST:event_b13ActionPerformed

    private void b15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b15ActionPerformed
     for(int i=0;i<8;i++)
     {
         if(Rname[i].equals("Satsuma"))
         {
             score+=2500;
             b15.setIcon(null);
             b15.setEnabled(false);
             src.setText(String.valueOf(score));
             result++;
         }
     }
     err++;
    }//GEN-LAST:event_b15ActionPerformed

    private void b16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b16ActionPerformed
     for(int i=0;i<8;i++)
     {
         if(Rname[i].equals("Kumquat"))
         {
             score+=2500;
             b16.setIcon(null);
             b16.setEnabled(false);
             src.setText(String.valueOf(score));
             result++;
         }
     }
     err++;
    }//GEN-LAST:event_b16ActionPerformed

    private void b17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b17ActionPerformed
      for(int i=0;i<8;i++)
     {
         if(Rname[i].equals("Date"))
         {
             score+=2500;
             b17.setEnabled(false);
             b17.setIcon(null);
             src.setText(String.valueOf(score));
             result++;
         }
     }
      err++;
    }//GEN-LAST:event_b17ActionPerformed

    private void b18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b18ActionPerformed
     for(int i=0;i<8;i++)
     {
         if(Rname[i].equals("Cherry"))
         {
             score+=2500;
             b18.setIcon(null);
             b18.setEnabled(false);
             src.setText(String.valueOf(score));
             result++;
         }
     }
     err++;
    }//GEN-LAST:event_b18ActionPerformed

    private void b19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b19ActionPerformed
     for(int i=0;i<8;i++)
     {
         if(Rname[i].equals("Pineapple"))
         {
             score+=2500;
             b19.setIcon(null);
             b19.setEnabled(false);
             src.setText(String.valueOf(score));
             result++;
         }
     }
     err++;
    }//GEN-LAST:event_b19ActionPerformed

    private void b20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b20ActionPerformed
       for(int i=0;i<8;i++)
     {
         if(Rname[i].equals("Kiwi fruit"))
         {
             score+=2500;
             b20.setIcon(null);
             b20.setEnabled(false);
             src.setText(String.valueOf(score));
             result++;
         }
     }
       err++;
    }//GEN-LAST:event_b20ActionPerformed

    private void b21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b21ActionPerformed
     for(int i=0;i<8;i++)
     {
         if(Rname[i].equals("Rambutan"))
         {
             score+=2500;
             b21.setIcon(null);
             b21.setEnabled(false);
             src.setText(String.valueOf(score));
             result++;
         }
     }
     err++;
    }//GEN-LAST:event_b21ActionPerformed

    private void b22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b22ActionPerformed
      for(int i=0;i<8;i++)
     {
         if(Rname[i].equals("Lichi"))
         {
             score+=2500;
             b22.setIcon(null);
             b22.setEnabled(false);
             src.setText(String.valueOf(score));
             result++;
         }
     }
      err++;
    }//GEN-LAST:event_b22ActionPerformed

    private void b23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b23ActionPerformed
      for(int i=0;i<8;i++)
     {
         if(Rname[i].equals("Jujube"))
         {
             score+=2500;
             b23.setIcon(null);
             b23.setEnabled(false);
             src.setText(String.valueOf(score));
             result++;
         }
     }
      err++;
    }//GEN-LAST:event_b23ActionPerformed

    private void b24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b24ActionPerformed
     for(int i=0;i<8;i++)
     {
         if(Rname[i].equals("Starfruit"))
         {
             score+=2500;
             b24.setIcon(null);
             b24.setEnabled(false);
             src.setText(String.valueOf(score));
             result++;
         }
     }
     err++;
    }//GEN-LAST:event_b24ActionPerformed

    private void b25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b25ActionPerformed
     for(int i=0;i<8;i++)
     {
         if(Rname[i].equals("Guava"))
         {
             score+=2500;
             b25.setIcon(null);
             b25.setEnabled(false);
             src.setText(String.valueOf(score));
             result++;
         }
     }
     err++;
    }//GEN-LAST:event_b25ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
      dead=1;
    }//GEN-LAST:event_formWindowClosed
public void setPIC()
{
    b1.setIcon(new javax.swing.ImageIcon("img\\apl.jpg"));
    b2.setIcon(new javax.swing.ImageIcon("img\\Quince.png"));
    b3.setIcon(new javax.swing.ImageIcon("img\\pomelos.jpg"));
    b4.setIcon(new javax.swing.ImageIcon("img\\orange.jpg"));
    b5.setIcon(new javax.swing.ImageIcon("img\\Avocado.jpg"));
    b6.setIcon(new javax.swing.ImageIcon("img\\grmango.jpg"));
    b7.setIcon(new javax.swing.ImageIcon("img\\Pomegranate.jpg"));
    b8.setIcon(new javax.swing.ImageIcon("img\\jackfruits.jpg"));
    b9.setIcon(new javax.swing.ImageIcon("img\\blackgrapes.jpg"));
    b10.setIcon(new javax.swing.ImageIcon("img\\Loquat.jpg"));
    b11.setIcon(new javax.swing.ImageIcon("img\\straw.jpg"));
    b12.setIcon(new javax.swing.ImageIcon("img\\Feijoa.jpg"));
    b13.setIcon(new javax.swing.ImageIcon("img\\Passionfruit.jpg"));
    b14.setIcon(new javax.swing.ImageIcon("img\\lemon.jpg"));
    b15.setIcon(new javax.swing.ImageIcon("img\\Satsuma.jpg"));
    b16.setIcon(new javax.swing.ImageIcon("img\\Kumquat.jpg"));
    b17.setIcon(new javax.swing.ImageIcon("img\\date.jpg"));
    b18.setIcon(new javax.swing.ImageIcon("img\\cherry.jpg"));
    b19.setIcon(new javax.swing.ImageIcon("img\\pineapl.jpg"));
    b20.setIcon(new javax.swing.ImageIcon("img\\Kiwi fruit.jpg"));
    b21.setIcon(new javax.swing.ImageIcon("img\\Rambutan.jpg"));
    b22.setIcon(new javax.swing.ImageIcon("img\\lichi.jpg"));
    b23.setIcon(new javax.swing.ImageIcon("img\\jujube.jpg"));
    b24.setIcon(new javax.swing.ImageIcon("img\\Starfruit.png"));
    b25.setIcon(new javax.swing.ImageIcon("img\\Guava.jpg"));
}
//public void update()
//{
//    String sql="select * from score order by score DESC";
//    try{
//        PreparedStatement st=null;
//        ResultSet rs=null;
//        st=con.prepareStatement(sql);
//        rs=st.executeQuery();
//        at.setModel(DbUtils.resultSetToTableModel(rs));
//    }catch(Exception e)
//    {
//        
//    }
//}
public void tr()
{
    b1.setEnabled(false);
    b2.setEnabled(false);
    b3.setEnabled(false);
    b4.setEnabled(false);
    b5.setEnabled(false);
    b6.setEnabled(false);
    b7.setEnabled(false);
    b8.setEnabled(false);
    b9.setEnabled(false);
    b10.setEnabled(false);
    b11.setEnabled(false);
    b12.setEnabled(false);
    b13.setEnabled(false);
    b14.setEnabled(false);
    b15.setEnabled(false);
    b16.setEnabled(false);
    b17.setEnabled(false);
    b18.setEnabled(false);
    b19.setEnabled(false);
    b20.setEnabled(false);
    b21.setEnabled(false);
    b22.setEnabled(false);
    b23.setEnabled(false);
    b24.setEnabled(false);
    b25.setEnabled(false);

}
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainP().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b10;
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b13;
    private javax.swing.JButton b14;
    private javax.swing.JButton b15;
    private javax.swing.JButton b16;
    private javax.swing.JButton b17;
    private javax.swing.JButton b18;
    private javax.swing.JButton b19;
    private javax.swing.JButton b2;
    private javax.swing.JButton b20;
    private javax.swing.JButton b21;
    private javax.swing.JButton b22;
    private javax.swing.JButton b23;
    private javax.swing.JButton b24;
    private javax.swing.JButton b25;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton jButton10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton l1;
    private javax.swing.JButton l2;
    private javax.swing.JButton l5;
    private javax.swing.JButton l6;
    private javax.swing.JButton l7;
    private javax.swing.JButton l8;
    private javax.swing.JPanel mainp;
    private javax.swing.JPanel mainpp;
    private javax.swing.JLabel p_lavel_value;
    private javax.swing.JProgressBar pbar;
    private javax.swing.JLabel src;
    private javax.swing.JButton stbt;
    private javax.swing.JLabel timeP;
    // End of variables declaration//GEN-END:variables
private int dead=0;
private int Game_running_flag=0;
private int button_flag=0;
int[] br=new int[6];

public void set_pbar()
{
    pbar.setValue(database_con.process_value("lav3"));
    p_lavel_value.setText(String.valueOf(pbar.getValue())+"%");
}
public void re_useable()
{
        score=0;
        err=0;
        result=0;
        stop=1;
        set_pbar();
}
    private void all_null() {
     b1.setIcon(null);
    b2.setIcon(null);
    b3.setIcon(null);
    b4.setIcon(null);
    b5.setIcon(null);
    b6.setIcon(null);
    b7.setIcon(null);
    b8.setIcon(null);
    b9.setIcon(null);
    b10.setIcon(null);
    b11.setIcon(null);
    b12.setIcon(null);
    b13.setIcon(null);
    b14.setIcon(null);
    b15.setIcon(null);
    b16.setIcon(null);
    b17.setIcon(null);
    b18.setIcon(null);
    b19.setIcon(null);
    b20.setIcon(null);
    b21.setIcon(null);
    b22.setIcon(null);
    b23.setIcon(null);
    b24.setIcon(null);
    b25.setIcon(null);
    l1.setText(null);
    l2.setText(null);
    l5.setText(null);
    l6.setText(null);
    l7.setText(null);
    l8.setText(null);
    }

    private void all_true() {
    b1.setEnabled(true);
    b2.setEnabled(true);
    b3.setEnabled(true);
    b4.setEnabled(true);
    b5.setEnabled(true);
    b6.setEnabled(true);
    b7.setEnabled(true);
    b8.setEnabled(true);
    b9.setEnabled(true);
    b10.setEnabled(true);
    b11.setEnabled(true);
    b12.setEnabled(true);
    b13.setEnabled(true);
    b14.setEnabled(true);
    b15.setEnabled(true);
    b16.setEnabled(true);
    b17.setEnabled(true);
    b18.setEnabled(true);
    b19.setEnabled(true);
    b20.setEnabled(true);
    b21.setEnabled(true);
    b22.setEnabled(true);
    b23.setEnabled(true);
    b24.setEnabled(true);
    b25.setEnabled(true);
    stbt.setEnabled(true);    
    }
class finish extends Thread{
      
      public void run(){
      while(true){
      if(result==8)
      {
          stop=1;
          score=((score/k)/(err+1))*850;
          src.setText(String.valueOf(score));
//          Scoreboard nnn=new Scoreboard();
//          nnn.setVisible(true);
          JOptionPane.showMessageDialog(null, "Screen clear !\n now Tottal Score:"+score);
          tr();
//          int pval=pbar.getValue();
//          float pfval=1/(k/100)+pval;
//          int cval=(int)pfval;
//          if(cval>=100)
//              cval=100;
//          System.out.print(pfval);
//          pbar.setValue(cval);
//          p_lavel_value.setText(p_lavel_value.getText()+String.valueOf(cval)+" %");
          this.suspend();
//          try {
//              PreparedStatement st=con.prepareStatement(sql);
//              st.setString(1, name);
//              st.setString(2, timeP.getText());
//              st.setInt(3, score);
//              st.executeUpdate();
//              //update();
//              this.suspend();
//          } catch (SQLException ex) {
//              Logger.getLogger(MainP.class.getName()).log(Level.SEVERE, null, ex);
//          }
      }
      if(k>=60)
      {
          stop=1;   
          tr();
          JOptionPane.showMessageDialog(null, "Time's Over!");
          k=0;
          this.suspend();
      }
      if(err-result>=3)
      {
          stop=1; 
          tr();
          JOptionPane.showMessageDialog(null, "You miss more than 3.\nGame's Over !");
          k=0;
          this.suspend();
      }
      if(dead==1)
      {
          this.suspend();
      }
      }
      }
}

class Stopwatch extends Thread{
      
      public void run(){

   for(k=0;;k++)
      {
              try
              {
               Thread.sleep(1000); 
               timeP.setText(String.valueOf(k));
               if(stop==1)
               {
                   this.suspend();
                   timeP.setText("0");
               }
               if (k>=55)
               {
                   Toolkit.getDefaultToolkit().beep(); 
               }
               }
               catch (InterruptedException ie)
               {  
               }
        }
  }
}
} 
    
